// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGefrzKAhV7c4OQEon2gYmsTIOpgciEs0',
    appId: '1:169156078368:web:d30f3465903fe81bb20545',
    messagingSenderId: '169156078368',
    projectId: 'mychat-d532e',
    authDomain: 'mychat-d532e.firebaseapp.com',
    storageBucket: 'mychat-d532e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5fBrWSduv-wvjlxdVOIV0He2XfhbuBVc',
    appId: '1:169156078368:android:710a2e602f968d16b20545',
    messagingSenderId: '169156078368',
    projectId: 'mychat-d532e',
    storageBucket: 'mychat-d532e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGlOOS8zhEvB1lSB4RLkBMdkrTxLXPNwM',
    appId: '1:169156078368:ios:7dd629322977135cb20545',
    messagingSenderId: '169156078368',
    projectId: 'mychat-d532e',
    storageBucket: 'mychat-d532e.firebasestorage.app',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGlOOS8zhEvB1lSB4RLkBMdkrTxLXPNwM',
    appId: '1:169156078368:ios:7dd629322977135cb20545',
    messagingSenderId: '169156078368',
    projectId: 'mychat-d532e',
    storageBucket: 'mychat-d532e.firebasestorage.app',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGefrzKAhV7c4OQEon2gYmsTIOpgciEs0',
    appId: '1:169156078368:web:8d5627de9f1310b0b20545',
    messagingSenderId: '169156078368',
    projectId: 'mychat-d532e',
    authDomain: 'mychat-d532e.firebaseapp.com',
    storageBucket: 'mychat-d532e.firebasestorage.app',
  );
}
